"""
Advisory service: generates a rich narrative using Google Gemini API.
Falls back to rule-based text if GOOGLE_API_KEY is not set.
"""

from __future__ import annotations
import os
from models.outputs import AnalysisResult, AdvisoryNoteResponse


SYSTEM_PROMPT = """You are an expert Indian renewable energy financial advisor.
You write concise, actionable advisory notes for utility-scale solar + BESS projects.
Use INR Crores as the currency unit. Be direct, data-driven, and professional.
Format output as markdown with clear sections."""


def _rule_based_note(result: AnalysisResult, project_name: str, consultant_name: str) -> AdvisoryNoteResponse:
    h = result.hybrid_financials
    s = result.solar_only_financials
    y1 = result.hybrid_year1

    md = f"""# Solar + BESS Advisory Note: {project_name}
*Prepared by {consultant_name}*

---

## Executive Summary
**Recommendation: {result.recommendation}**

{result.recommendation_reason}

---

## Financial Highlights

| Metric | Solar Only | Solar + BESS | Incremental |
|--------|-----------|-------------|-------------|
| NPV (₹ Cr) | {s.npv_cr:.1f} | {h.npv_cr:.1f} | {result.incremental_npv_cr:.1f} |
| IRR (%) | {s.irr_percent or "N/A"} | {h.irr_percent or "N/A"} | — |
| CAPEX (₹ Cr) | {s.total_capex_cr:.1f} | {h.total_capex_cr:.1f} | — |
| BESS Payback | — | {h.simple_payback_years or "N/A"} yrs | — |

---

## Year-1 Revenue Stack (Hybrid)

| Stream | ₹ Crores |
|--------|----------|
| Base PPA Revenue | {y1.base_ppa_revenue_cr:.2f} |
| DSM Savings | {y1.dsm_savings_cr:.2f} |
| Clipping Recovery | {y1.clipping_recovery_cr:.2f} |
| Curtailment Recovery | {y1.curtailment_recovery_cr:.2f} |
| Arbitrage | {y1.arbitrage_cr:.2f} |
| Ancillary Services | {y1.ancillary_cr:.2f} |
| **Total Revenue** | **{y1.total_revenue_cr:.2f}** |

---

## Key Risks
- Battery degradation erodes arbitrage revenue over time; monitor via BESS management system.
- Regulatory risk: peak sell tariffs and DSM norms may change under CERC revisions.
- Actual clipping/curtailment may vary from modelled assumptions.

---

*This note is auto-generated by Solar BESS Advisor. Verify all assumptions with project-specific data.*
"""
    return AdvisoryNoteResponse(
        title=f"Advisory Note: {project_name}",
        markdown=md,
        recommendation=result.recommendation,
    )


async def generate_advisory_note(
    result: AnalysisResult,
    project_name: str,
    consultant_name: str,
) -> AdvisoryNoteResponse:
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        return _rule_based_note(result, project_name, consultant_name)

    try:
        import google.generativeai as genai
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(
            model_name="gemini-1.5-pro",
            system_instruction=SYSTEM_PROMPT,
        )

        h = result.hybrid_financials
        s = result.solar_only_financials
        y1 = result.hybrid_year1

        prompt = f"""Generate a professional advisory note for project '{project_name}' for consultant '{consultant_name}'.

Key financials:
- Solar Only NPV: ₹{s.npv_cr:.1f} Cr, IRR: {s.irr_percent}%
- Hybrid NPV: ₹{h.npv_cr:.1f} Cr, IRR: {h.irr_percent}%
- Incremental NPV from BESS: ₹{result.incremental_npv_cr:.1f} Cr
- BESS Payback Period: {h.simple_payback_years} years
- Year-1 Incremental Revenue: ₹{result.incremental_revenue_cr:.2f} Cr
- Year-1 Revenue breakdown (hybrid):
  - Base PPA: ₹{y1.base_ppa_revenue_cr:.2f} Cr
  - DSM Savings: ₹{y1.dsm_savings_cr:.2f} Cr
  - Clipping Recovery: ₹{y1.clipping_recovery_cr:.2f} Cr
  - Curtailment Recovery: ₹{y1.curtailment_recovery_cr:.2f} Cr
  - Arbitrage: ₹{y1.arbitrage_cr:.2f} Cr
  - Ancillary: ₹{y1.ancillary_cr:.2f} Cr
- Recommendation: {result.recommendation}
- Reason: {result.recommendation_reason}

Warnings:
{chr(10).join(f'- [{w.severity.upper()}] {w.message}' for w in result.warnings) or 'None'}

Write a 400-600 word professional advisory note in markdown. Include:
1. Executive Summary with clear recommendation
2. Financial Analysis table
3. Revenue Stack Analysis 
4. Risk Assessment (India-specific regulatory and market risks)
5. Recommendation with specific action items
"""
        response = await model.generate_content_async(prompt)
        return AdvisoryNoteResponse(
            title=f"Advisory Note: {project_name}",
            markdown=response.text,
            recommendation=result.recommendation,
        )
    except Exception as e:
        # Fallback to rule-based on any Gemini error
        note = _rule_based_note(result, project_name, consultant_name)
        note.markdown += f"\n\n> *AI note generation failed: {str(e)[:100]}. Rule-based note shown.*"
        return note
